service: fontcache

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:PutObject"
      Resource: "arn:aws:s3:::syon-fontcache/*"

functions:
  hello:
    handler: handler.hello
