service: fontcache

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:PutObject"
      Resource: "arn:aws:s3:::syon-fontcache/*"
  environment:
    DEBUG: "*"

functions:
  main:
    handler: handler.main
